// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDigqbLN5kysUBqYud7UmkM52fUJdgSZfA',
    appId: '1:350869063975:web:62180915ce0d93831fc102',
    messagingSenderId: '350869063975',
    projectId: 'orientation-app-5c7ef',
    authDomain: 'orientation-app-5c7ef.firebaseapp.com',
    storageBucket: 'orientation-app-5c7ef.appspot.com',
    measurementId: 'G-2EFK11KEBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtCD93nHjSSp7vFd3V6MKGgDzOzvEtFQ',
    appId: '1:350869063975:android:5a803b114ee5e4f31fc102',
    messagingSenderId: '350869063975',
    projectId: 'orientation-app-5c7ef',
    storageBucket: 'orientation-app-5c7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcU9HGxf6uSRedxRZSlsolab0lzhhjXlw',
    appId: '1:350869063975:ios:29b51e6a3ff6cbee1fc102',
    messagingSenderId: '350869063975',
    projectId: 'orientation-app-5c7ef',
    storageBucket: 'orientation-app-5c7ef.appspot.com',
    iosBundleId: 'com.example.orientationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcU9HGxf6uSRedxRZSlsolab0lzhhjXlw',
    appId: '1:350869063975:ios:29b51e6a3ff6cbee1fc102',
    messagingSenderId: '350869063975',
    projectId: 'orientation-app-5c7ef',
    storageBucket: 'orientation-app-5c7ef.appspot.com',
    iosBundleId: 'com.example.orientationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDigqbLN5kysUBqYud7UmkM52fUJdgSZfA',
    appId: '1:350869063975:web:b2ae57277a6e4dda1fc102',
    messagingSenderId: '350869063975',
    projectId: 'orientation-app-5c7ef',
    authDomain: 'orientation-app-5c7ef.firebaseapp.com',
    storageBucket: 'orientation-app-5c7ef.appspot.com',
    measurementId: 'G-1DLLF8HP83',
  );
}
